version: "3.7"
services:
  core:
    image: ibwighane/tomis-core
    restart: always
    ports:
      - 40000:4000
  app:
    image: ibwighane/tomis-app
    restart: always
    ports:
      - 30000:3000
